apiVersion: v1
kind: Service
metadata:
  name: springboot
  namespace: default    # Kubernets namespace
  labels:
    app: springboot
    service: springboot
    env: nonprod
spec:
  selector:
    app: springboot
    service: springboot
    env: nonprod
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
